nightswatch:
  channel: '#nightswatch'
  exclude_labels:
    - no seal
  members:
    - carlescere
    - memosstilvi
    - michaelkyriacou
    - cosenal
tag:
  channel: '#khaleesi-tag'
  exclude_labels:
    - no seal
  members:
    - anafuiorea
    - eddking
    - marcindobry
    - viralpickaxe
    - willfrew
drogon:
  channel: '#drogon'
  exclude_labels:
    - no seal
  members:
    - alantreadway
    - PhilippeMorier
    - adefreitas
    - msempere
